#!/usr/bin/env python3
"""
Junior-class precision diagnostic experiment.

EXPERIMENT ONLY — no production artifacts modified.
Results saved to /opt/job-market-analytics/models/experiments/

Investigates two hypotheses for junior precision = 0.539 from Phase 1:
(a) Boilerplate stripping removes junior-signal language from JDs
(b) class_weight='balanced' over-expands the junior decision boundary (~13x upweight)

Approach:
  - 2 text sources x 3 class weights = 6 runs
  - STRIPPED embeddings: loaded directly from job_postings.embedding (already paid for,
    generated by embed_jobs.py from boilerplate-stripped text). Only re-encode the
    tiny fraction of jobs (<1%) without a stored embedding.
  - UNSTRIPPED embeddings: one model.encode() pass on raw description text (genuinely
    different input — cannot reuse stored embeddings).
  - Same training set, same 80/20 stratified split (random_state=42) as Phase 1

Run:
    /opt/job-market-analytics/.venv/bin/python \\
        /opt/job-market-analytics/python/exp_level_junior_diagnostic.py
"""

import csv
import logging
import os
import re
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

import joblib
import numpy as np
import psycopg2
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, precision_recall_fscore_support
from sklearn.model_selection import train_test_split

sys.path.insert(0, str(Path(__file__).resolve().parent))
from text_utils import compute_boilerplate_sets, strip_boilerplate

load_dotenv(Path(__file__).parent.parent / '.env')

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s', datefmt='%H:%M:%S')
log = logging.getLogger(__name__)

EXPERIMENTS_DIR = Path('/opt/job-market-analytics/models/experiments')
REPORT_PATH     = EXPERIMENTS_DIR / 'junior_diagnostic_report.md'
MODEL_NAME      = 'all-MiniLM-L6-v2'
DESC_CHARS      = 1500
BATCH_SIZE      = 64

# ── Title-certain label regexes (identical to train_exp_level_classifier.py) ──
JUNIOR_RE = re.compile(
    r'\b(?:intern(?:ship)?|junior|graduate?|entry[\s\-]level|early[\s\-]career|'
    r'apprentice|trainee|new[\s\-]grad|university[\s\-]grad|campus)\b'
    r'|\bjr\.?(?=\W|$)',
    re.IGNORECASE,
)
SENIOR_RE = re.compile(r'\b(?:senior|staff|principal)\b|\bsr\.?(?=\W|$)', re.IGNORECASE)
LEAD_RE   = re.compile(r'\b(?:lead|manager|director|vp|head\s+of)\b', re.IGNORECASE)

# Junior-signal phrases to search for in boilerplate-removed text
JUNIOR_SIGNAL_PHRASES = [
    'early career', 'new grad', 'entry level', 'entry-level',
    'recent graduate', 'no experience', 'junior', 'internship',
    'apprentice', 'trainee', 'first job', 'early-career',
]

# Experiment configurations
CONFIGS = [
    ('stripped',   'balanced'),
    ('stripped',   {'junior': 8,  'senior': 1, 'lead': 1}),
    ('stripped',   {'junior': 4,  'senior': 1, 'lead': 1}),
    ('unstripped', 'balanced'),
    ('unstripped', {'junior': 8,  'senior': 1, 'lead': 1}),
    ('unstripped', {'junior': 4,  'senior': 1, 'lead': 1}),
]


def get_conn():
    return psycopg2.connect(
        host=os.environ['PGHOST'],
        port=os.environ.get('PGPORT', '5432'),
        dbname=os.environ['PGDATABASE'],
        user=os.environ['PGUSER'],
        password=os.environ['PGPASSWORD'],
    )


def label_from_title(title: str):
    if JUNIOR_RE.search(title or ''):
        return 'junior'
    if LEAD_RE.search(title or ''):
        return 'lead'
    if SENIOR_RE.search(title or ''):
        return 'senior'
    return None


def weight_label(cw):
    """Human-readable label for a class_weight config."""
    if cw == 'balanced':
        return 'balanced (~13x)'
    return f"manual {cw['junior']}x"


# ── Stored embedding loader ────────────────────────────────────────────────────

def load_stored_embeddings(conn, job_ids: list) -> dict:
    """Load pre-computed embeddings from job_postings.embedding.

    These were generated by embed_jobs.py from boilerplate-stripped text using the
    same all-MiniLM-L6-v2 model (max_seq_length=256). Since both stored and classifier
    inputs exceed the 256-token limit, truncation happens at the same point — embeddings
    are functionally identical to what we'd compute from 1500-char stripped descriptions.
    """
    log.info(f"Loading stored embeddings for {len(job_ids):,} jobs...")
    t0 = time.time()
    with conn.cursor() as cur:
        cur.execute(
            "SELECT job_id, embedding FROM job_postings WHERE job_id = ANY(%s) "
            "AND embedding IS NOT NULL",
            (job_ids,)
        )
        rows = cur.fetchall()
    emb_by_id = {row[0]: np.fromstring(row[1].strip('[]'), sep=',', dtype=np.float32)
                 for row in rows}
    log.info(f"Loaded {len(emb_by_id):,} stored embeddings in {time.time()-t0:.1f}s "
             f"(coverage: {100*len(emb_by_id)/len(job_ids):.1f}%)")
    return emb_by_id


# ── 1. Load data ──────────────────────────────────────────────────────────────

def load_data(conn):
    log.info("Fetching company descriptions for boilerplate detection...")
    with conn.cursor() as cur:
        cur.execute("""
            SELECT jp.company_id, COALESCE(jp.description_text, '')
            FROM job_postings jp
            WHERE jp.status='raw' AND jp.data_tier=1 AND jp.domain IS NOT NULL
        """)
        all_rows = cur.fetchall()

    company_descs: dict = defaultdict(list)
    for cid, desc in all_rows:
        company_descs[cid].append(desc)

    log.info(f"Computing boilerplate for {len(company_descs):,} companies...")
    t0 = time.time()
    bp_by_company = compute_boilerplate_sets(company_descs)
    log.info(f"Done in {time.time()-t0:.1f}s")

    # Fetch title-certain jobs that also have a stored embedding so stripped and
    # unstripped configurations train on the identical job set.
    log.info("Loading title-certain training examples (with stored embeddings only)...")
    with conn.cursor() as cur:
        cur.execute("""
            SELECT jp.job_id, jp.company_id, r.role_name,
                   COALESCE(jp.description_text, ''), jp.embedding
            FROM job_postings jp
            JOIN roles r ON r.role_id = jp.role_id
            WHERE jp.status='raw' AND jp.data_tier=1 AND jp.domain IS NOT NULL
              AND jp.embedding IS NOT NULL
        """)
        job_rows = cur.fetchall()

    job_ids, company_ids, titles, raw_descs, labels, stored_embs = [], [], [], [], [], []
    for job_id, cid, role_name, desc, emb in job_rows:
        lbl = label_from_title(role_name)
        if lbl is None:
            continue
        job_ids.append(job_id)
        company_ids.append(cid)
        titles.append(role_name)
        raw_descs.append(desc)
        labels.append(lbl)
        # pgvector returns as a bracketed string; parse it directly
        stored_embs.append(np.fromstring(emb.strip('[]'), sep=',', dtype=np.float32))

    dist = Counter(labels)
    log.info(f"Loaded {len(labels):,} examples with stored embeddings: {dict(dist)}")
    return job_ids, company_ids, titles, raw_descs, labels, stored_embs, bp_by_company, dist


# ── 2. Boilerplate impact analysis ───────────────────────────────────────────

def analyze_boilerplate_impact(job_ids, titles, raw_descs, labels, bp_by_company, company_ids):
    log.info("Analyzing boilerplate impact on junior jobs...")
    junior_idx = [i for i, l in enumerate(labels) if l == 'junior']

    chars_removed_list = []
    signal_removed_count = 0
    signal_examples = []

    for i in junior_idx:
        cid = company_ids[i]
        raw = raw_descs[i]
        bp_set = bp_by_company.get(cid, set())
        stripped = strip_boilerplate(raw, bp_set)

        removed_chars = len(raw) - len(stripped)
        chars_removed_list.append(removed_chars)

        # Find which signal phrases appear in raw but not stripped
        raw_lower = raw.lower()
        stripped_lower = stripped.lower()
        found_phrases = []
        for phrase in JUNIOR_SIGNAL_PHRASES:
            if phrase in raw_lower and phrase not in stripped_lower:
                found_phrases.append(phrase)

        if found_phrases:
            signal_removed_count += 1
            if len(signal_examples) < 5:
                # Build a snippet around the first found phrase in the raw text
                phrase = found_phrases[0]
                idx = raw_lower.find(phrase)
                snippet_start = max(0, idx - 40)
                snippet_end = min(len(raw), idx + len(phrase) + 80)
                snippet = raw[snippet_start:snippet_end].replace('\n', ' ')
                signal_examples.append({
                    'job_id': job_ids[i],
                    'title': titles[i],
                    'phrases': found_phrases,
                    'snippet': snippet,
                })

    n = len(junior_idx)
    avg_removed = np.mean(chars_removed_list) if chars_removed_list else 0
    median_removed = np.median(chars_removed_list) if chars_removed_list else 0
    pct_signal_removed = 100 * signal_removed_count / n if n else 0

    print("\n" + "=" * 65)
    print("BOILERPLATE IMPACT ON JUNIOR JOBS")
    print("=" * 65)
    print(f"Junior jobs analyzed: {n}")
    print(f"Avg chars removed by stripping: {avg_removed:.0f}")
    print(f"Median chars removed:           {median_removed:.0f}")
    print(f"Max chars removed:              {max(chars_removed_list, default=0)}")
    print(f"Jobs with 0 chars removed:      {sum(1 for c in chars_removed_list if c == 0)}")
    print()
    print(f"Jobs where stripping removed a junior-signal phrase: "
          f"{signal_removed_count} / {n} ({pct_signal_removed:.1f}%)")
    print(f"Phrases checked: {', '.join(JUNIOR_SIGNAL_PHRASES)}")
    print()
    if signal_examples:
        print("Examples of removed junior-signal text:")
        for ex in signal_examples:
            print(f"  title: {ex['title']}")
            print(f"  phrases removed: {ex['phrases']}")
            print(f"  context: ...{ex['snippet']}...")
            print()
    else:
        print("No examples found (no junior-signal phrases removed by stripping).")
    print("=" * 65 + "\n")

    return {
        'n_junior': n,
        'avg_chars_removed': avg_removed,
        'median_chars_removed': median_removed,
        'signal_removed_count': signal_removed_count,
        'pct_signal_removed': pct_signal_removed,
        'signal_examples': signal_examples,
    }


# ── 3. Build both text sets ───────────────────────────────────────────────────

def build_text_stripped(title, raw_desc, bp_set):
    title_clean = (title or '')[:200]
    desc = strip_boilerplate(raw_desc or '', bp_set)[:DESC_CHARS]
    return f"{title_clean}. {desc}"


def build_text_unstripped(title, raw_desc):
    title_clean = (title or '')[:200]
    desc = (raw_desc or '')[:DESC_CHARS]
    return f"{title_clean}. {desc}"


# ── 4. Encode ─────────────────────────────────────────────────────────────────

def encode(model, texts, label):
    log.info(f"Encoding {len(texts):,} texts ({label})...")
    t0 = time.time()
    X = model.encode(texts, batch_size=BATCH_SIZE, show_progress_bar=True, convert_to_numpy=True)
    log.info(f"Encoded in {time.time()-t0:.1f}s")
    return X


# ── 5. Train one configuration ────────────────────────────────────────────────

def run_config(X, y, class_weight, config_name):
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )
    clf = LogisticRegression(
        class_weight=class_weight,
        max_iter=1000,
        random_state=42,
        C=1.0,
    )
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_val)

    classes = sorted(clf.classes_.tolist())
    report = classification_report(y_val, y_pred, labels=classes, digits=3, output_dict=True)

    # Save experiment artifact
    artifact = {
        'classifier': clf,
        'config_name': config_name,
        'class_weight': class_weight,
        'classes': classes,
        'val_report': report,
    }
    path = EXPERIMENTS_DIR / f"exp_{config_name.replace(' ', '_').replace('/', '_')}.pkl"
    joblib.dump(artifact, path)

    return report, classes


# ── 6. Main ───────────────────────────────────────────────────────────────────

def main():
    conn = get_conn()
    job_ids, company_ids, titles, raw_descs, labels, stored_embs, bp_by_company, dist = \
        load_data(conn)
    conn.close()

    # Boilerplate impact check (hypothesis a)
    bp_impact = analyze_boilerplate_impact(
        job_ids, titles, raw_descs, labels, bp_by_company, company_ids
    )

    # STRIPPED embeddings: already computed and stored in job_postings.embedding.
    # No encode pass needed — just stack the vectors loaded from the DB.
    log.info("Assembling stored embeddings for stripped configurations...")
    X_stripped = np.stack(stored_embs)
    log.info(f"X_stripped shape: {X_stripped.shape}  (loaded from DB, no re-encoding)")

    # UNSTRIPPED embeddings: raw description text — genuinely different input.
    # One encode pass required.
    unstripped_texts = [
        build_text_unstripped(titles[i], raw_descs[i])
        for i in range(len(labels))
    ]
    log.info(f"Loading model {MODEL_NAME} for unstripped encoding...")
    model = SentenceTransformer(MODEL_NAME)
    model.max_seq_length = 256
    X_unstripped = encode(model, unstripped_texts, 'unstripped')

    y = np.array(labels)

    # Run 6 configurations
    results = []
    for text_source, class_weight in CONFIGS:
        X = X_stripped if text_source == 'stripped' else X_unstripped
        config_name = f"{text_source}_{weight_label(class_weight)}"
        log.info(f"Training: {config_name}")
        t0 = time.time()
        report, classes = run_config(X, y, class_weight, config_name)
        log.info(f"Done in {time.time()-t0:.1f}s")
        results.append((text_source, class_weight, report, classes))

    # ── Print comparison table ──────────────────────────────────────────────
    print("\n" + "=" * 80)
    print("6-CONFIGURATION COMPARISON TABLE")
    print("=" * 80)
    header = (f"{'text':>10}  {'weight':>16}  "
              f"{'jr_prec':>8}  {'jr_rec':>7}  {'jr_f1':>6}  "
              f"{'lead_f1':>8}  {'sr_f1':>6}  {'acc':>5}")
    print(header)
    print("-" * 80)

    viable = []
    for text_source, class_weight, report, classes in results:
        jr  = report.get('junior', {})
        ld  = report.get('lead',   {})
        sr  = report.get('senior', {})
        acc = report.get('accuracy', 0)

        jr_p = jr.get('precision', 0)
        jr_r = jr.get('recall', 0)
        jr_f = jr.get('f1-score', 0)
        ld_f = ld.get('f1-score', 0)
        sr_f = sr.get('f1-score', 0)

        flag = ' ← viable?' if jr_p >= 0.75 and jr_r >= 0.70 else ''
        if jr_p >= 0.75 and jr_r >= 0.70:
            viable.append((text_source, class_weight, jr_p, jr_r, jr_f))

        wt_str = weight_label(class_weight)
        print(f"{text_source:>10}  {wt_str:>16}  "
              f"{jr_p:>8.3f}  {jr_r:>7.3f}  {jr_f:>6.3f}  "
              f"{ld_f:>8.3f}  {sr_f:>6.3f}  {acc:>5.3f}{flag}")

    print("=" * 80)

    # ── Assessment ─────────────────────────────────────────────────────────
    print("\nASSESSMENT")
    print("-" * 40)
    if viable:
        print(f"Configurations clearing precision>=0.75, recall>=0.70:")
        for v in viable:
            print(f"  text={v[0]}, weight={weight_label(v[1])}: "
                  f"precision={v[2]:.3f}, recall={v[3]:.3f}, F1={v[4]:.3f}")
    else:
        print("NO configuration clears the production-viable bar "
              "(precision>=0.75 AND recall>=0.70).")

    # ── Save markdown report ────────────────────────────────────────────────
    lines = [
        "# Junior Precision Diagnostic Report\n",
        "**Experiment only — no production artifacts modified.**\n",
        f"\nModel: {MODEL_NAME} | DESC_CHARS={DESC_CHARS} | same train/val split as Phase 1\n",
        "\n## Hypothesis (a): Boilerplate Stripping Impact on Junior Jobs\n",
        f"- Junior jobs analyzed: {bp_impact['n_junior']}\n",
        f"- Avg chars removed by stripping: {bp_impact['avg_chars_removed']:.0f}\n",
        f"- Median chars removed: {bp_impact['median_chars_removed']:.0f}\n",
        f"- Jobs where stripping removed a junior-signal phrase: "
        f"{bp_impact['signal_removed_count']} / {bp_impact['n_junior']} "
        f"({bp_impact['pct_signal_removed']:.1f}%)\n",
        f"- Signal phrases checked: {', '.join(JUNIOR_SIGNAL_PHRASES)}\n",
    ]
    if bp_impact['signal_examples']:
        lines.append("\nExamples of removed junior-signal text:\n")
        for ex in bp_impact['signal_examples']:
            lines.append(f"- **{ex['title']}**: phrases=`{ex['phrases']}` "
                         f"context: `...{ex['snippet'][:120]}...`\n")
    else:
        lines.append("\nNo junior-signal phrases were removed by stripping on any junior job.\n")

    lines.append("\n## Hypothesis (b): Class Weight Impact\n")
    lines.append(
        "| text | weight | jr_prec | jr_rec | jr_f1 | lead_f1 | senior_f1 | acc |\n"
        "|---|---|---|---|---|---|---|---|\n"
    )
    for text_source, class_weight, report, classes in results:
        jr  = report.get('junior', {})
        ld  = report.get('lead',   {})
        sr  = report.get('senior', {})
        acc = report.get('accuracy', 0)
        wt_str = weight_label(class_weight)
        flag = ' ✓' if jr.get('precision',0) >= 0.75 and jr.get('recall',0) >= 0.70 else ''
        lines.append(
            f"| {text_source} | {wt_str} | {jr.get('precision',0):.3f} | "
            f"{jr.get('recall',0):.3f} | {jr.get('f1-score',0):.3f} | "
            f"{ld.get('f1-score',0):.3f} | {sr.get('f1-score',0):.3f} | "
            f"{acc:.3f} |{flag}\n"
        )

    lines.append("\n## Assessment\n")
    if viable:
        for v in viable:
            lines.append(f"- **{v[0]} + {weight_label(v[1])}** clears the bar: "
                         f"precision={v[2]:.3f}, recall={v[3]:.3f}, F1={v[4]:.3f}\n")
    else:
        lines.append(
            "No configuration clears the production-viable bar "
            "(precision >= 0.75 AND recall >= 0.70).\n"
        )

    REPORT_PATH.write_text(''.join(lines))
    log.info(f"Report saved: {REPORT_PATH}")
    print(f"\nReport: {REPORT_PATH}")
    print("Done.")


if __name__ == '__main__':
    main()
