#!/usr/bin/env python3
"""
expand_companies.py

Adds ~500 high-probability Greenhouse companies to discovered_companies.
These are organized by industry and selected specifically because they
are known to hire data, analytics, BI, and ML roles.

Run once:
    python python/expand_companies.py --apply

Then run discovery to probe which ones actually have open roles:
    python python/discover_companies.py --apply --source refresh
"""

import os
import hashlib
import logging
from pathlib import Path
from datetime import datetime, timezone

from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import DictCursor

load_dotenv(dotenv_path=Path(__file__).resolve().parents[1] / ".env")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)

# ============================================================
# ~500 HIGH-PROBABILITY GREENHOUSE COMPANIES
# Organized by sector. Token = Greenhouse board token.
# These are companies known to use Greenhouse AND hire data roles.
# ============================================================

COMPANIES = [

    # ── FINTECH / PAYMENTS ──────────────────────────────────
    ("Stripe",              "stripe"),
    ("Brex",                "brex"),
    ("Ramp",                "ramp"),
    ("Affirm",              "affirm"),
    ("Plaid",               "plaid"),
    ("Chime",               "chime"),
    ("Robinhood",           "robinhood"),
    ("Coinbase",            "coinbase"),
    ("Kraken",              "kraken"),
    ("Gemini",              "gemini"),
    ("Marqeta",             "marqeta"),
    ("Adyen",               "adyen"),
    ("Checkout",            "checkout"),
    ("Rapyd",               "rapyd"),
    ("Flywire",             "flywire"),
    ("Payoneer",            "payoneer"),
    ("Nuvei",               "nuvei"),
    ("Paysafe",             "paysafe"),
    ("Flutterwave",         "flutterwave"),
    ("Chipper Cash",        "chippercash"),
    ("Mercury",             "mercury"),
    ("Rho",                 "rhobusiness"),
    ("Airwallex",           "airwallex"),
    ("Wise",                "wise"),
    ("Transferwise",        "transferwise"),
    ("Revolut",             "revolut"),
    ("Monzo",               "monzo"),
    ("Starling",            "starlingbank"),
    ("N26",                 "n26"),
    ("Nubank",              "nubank"),
    ("Neon",                "neonpagamentos"),
    ("C6 Bank",             "c6bank"),
    ("Creditas",            "creditas"),
    ("Kavak",               "kavak"),

    # ── LENDING / CREDIT ────────────────────────────────────
    ("Upstart",             "upstart"),
    ("LendingClub",         "lendingclub"),
    ("SoFi",                "sofi"),
    ("Blend",               "blend"),
    ("Better",              "better"),
    ("Avant",               "avant"),
    ("Prosper",             "prosper"),
    ("Funding Circle",      "fundingcircle"),
    ("Kabbage",             "kabbage"),
    ("Greensky",            "greensky"),
    ("Oportun",             "oportun"),
    ("Earnin",              "activehours"),
    ("Dave",                "dave"),
    ("Possible Finance",    "possiblefinance"),
    ("Cleo",                "cleo"),

    # ── INSURANCE / INSURTECH ───────────────────────────────
    ("Lemonade",            "lemonade"),
    ("Root Insurance",      "joinroot"),
    ("Hippo",               "hippo"),
    ("Kin Insurance",       "kin"),
    ("Openly",              "openly"),
    ("Branch",              "ourbranch"),
    ("Clearcover",          "clearcover"),
    ("Metromile",           "metromile"),
    ("Next Insurance",      "nextinsurance"),
    ("Coalition",           "thecoalition"),
    ("At-Bay",              "atbay"),
    ("Cowbell",             "cowbell"),
    ("Corvus",              "corvusinsurance"),
    ("Pie Insurance",       "pieinsurance"),
    ("Vouch",               "vouch"),
    ("Ethos",               "ethos"),
    ("Haven Life",          "havenlife"),
    ("Ladder",              "ladderlife"),
    ("Bestow",              "bestow"),
    ("Fabric",              "meetfabric"),

    # ── DATA / ANALYTICS PLATFORMS ──────────────────────────
    ("Databricks",          "databricks"),
    ("Snowflake",           "snowflake"),
    ("dbt Labs",            "dbtlabs"),
    ("Fivetran",            "fivetran"),
    ("Hightouch",           "hightouch"),
    ("Census",              "census"),
    ("Airbyte",             "airbyte"),
    ("Stitch",              "stitchdata"),
    ("Talend",              "talend"),
    ("Informatica",         "informatica"),
    ("MicroStrategy",       "microstrategy"),
    ("Sisense",             "sisense"),
    ("Sigma Computing",     "sigmacomputing"),
    ("Hex",                 "hex"),
    ("Mode Analytics",      "modeanalytics"),
    ("Preset",              "preset"),
    ("Metabase",            "metabase"),
    ("Looker",              "looker"),
    ("ThoughtSpot",         "thoughtspot"),
    ("Alation",             "alation"),
    ("Atlan",               "atlan"),
    ("Collibra",            "collibra"),
    ("Monte Carlo",         "montecarlodata"),
    ("Anomalo",             "anomalo"),
    ("Bigeye",              "bigeye"),
    ("Acceldata",           "acceldata"),
    ("Soda",                "soda"),
    ("Great Expectations",  "superconductive"),
    ("Starburst",           "starburstdata"),
    ("Imply",               "imply"),
    ("SingleStore",         "singlestore"),
    ("CockroachLabs",       "cockroachlabs"),
    ("PlanetScale",         "planetscale"),
    ("Neon DB",             "neondatabase"),
    ("Supabase",            "supabase"),
    ("Hasura",              "hasura"),
    ("Rockset",             "rockset"),
    ("Pinecone",            "pinecone"),
    ("Weaviate",            "weaviate"),
    ("Qdrant",              "qdrant"),
    ("Chroma",              "trychroma"),
    ("Turso",               "turso"),
    ("Motherduck",          "motherduck"),
    ("Hydra",               "hydra"),
    ("Clickhouse",          "clickhouse"),
    ("StarTree",            "startree"),
    ("Druid",               "imply"),
    ("Grafana Labs",        "grafanalabs"),
    ("Chronosphere",        "chronosphere"),
    ("Honeycomb",           "honeycomb"),
    ("Lightstep",           "lightstep"),
    ("Observe",             "observeinc"),
    ("Coralogix",           "coralogix"),
    ("Sumo Logic",          "sumologic"),
    ("Elastic",             "elastic"),
    ("Splunk",              "splunk"),
    ("Datadog",             "datadoghq"),
    ("New Relic",           "newrelic"),
    ("Dynatrace",           "dynatrace"),
    ("AppDynamics",         "appdynamics"),

    # ── ML / AI ─────────────────────────────────────────────
    ("Anthropic",           "anthropic"),
    ("OpenAI",              "openai"),
    ("Scale AI",            "scaleai"),
    ("Cohere",              "cohere"),
    ("Mistral",             "mistral"),
    ("Hugging Face",        "huggingface"),
    ("Weights & Biases",    "wandb"),
    ("Determined AI",       "determined-ai"),
    ("Anyscale",            "anyscale"),
    ("Together AI",         "togetherai"),
    ("Groq",                "groq"),
    ("Cerebras",            "cerebras"),
    ("SambaNova",           "sambanova"),
    ("Inflection",          "inflection"),
    ("Adept",               "adept"),
    ("Runway",              "runwayml"),
    ("Stability AI",        "stabilityai"),
    ("Midjourney",          "midjourney"),
    ("Character AI",        "characterai"),
    ("Jasper",              "jasper"),
    ("Writer",              "writer"),
    ("Glean",               "glean"),
    ("Vectara",             "vectara"),
    ("Moveworks",           "moveworks"),
    ("Avaamo",              "avaamo"),
    ("Cognigy",             "cognigy"),
    ("Kore AI",             "kore"),
    ("Rasa",                "rasa"),
    ("Labelbox",            "labelbox"),
    ("Scale",               "scale"),
    ("Appen",               "appen"),
    ("Lionbridge AI",       "lionbridge"),
    ("Surge AI",            "surgehq"),
    ("DataAnnotation",      "dataannotation"),
    ("Invisible AI",        "invisible"),
    ("Dataloop",            "dataloop"),
    ("Encord",              "encord"),
    ("Aquarium",            "aquariumlearning"),
    ("Voxel51",             "voxel51"),
    ("Roboflow",            "roboflow"),
    ("Landing AI",          "landingai"),
    ("Clarifai",            "clarifai"),
    ("Tractable",           "tractable"),
    ("Argo AI",             "argo"),
    ("Aurora",              "aurora"),
    ("Nuro",                "nuro"),
    ("Waymo",               "waymo"),
    ("Cruise",              "cruise"),
    ("Zoox",                "zoox"),
    ("Motional",            "motional"),
    ("TuSimple",            "tusimple"),
    ("Embark",              "embark"),
    ("Kodiak",              "kodiak"),

    # ── CLOUD / INFRASTRUCTURE ──────────────────────────────
    ("Cloudflare",          "cloudflare"),
    ("Fastly",              "fastly"),
    ("Akamai",              "akamai"),
    ("Cloudsmith",          "cloudsmith"),
    ("Netlify",             "netlify"),
    ("Vercel",              "vercel"),
    ("Railway",             "railway"),
    ("Render",              "render"),
    ("Fly.io",              "fly"),
    ("Supabase",            "supabase"),
    ("PlanetScale",         "planetscale"),
    ("Neon",                "neondatabase"),
    ("Temporal",            "temporal"),
    ("Pulumi",              "pulumi"),
    ("Terraform",           "hashicorp"),
    ("HashiCorp",           "hashicorp"),
    ("Vault",               "hashicorp"),
    ("Consul",              "hashicorp"),
    ("Nomad",               "hashicorp"),
    ("Packer",              "hashicorp"),
    ("Chef",                "chef"),
    ("Puppet",              "puppet"),
    ("Ansible",             "redhat"),
    ("GitLab",              "gitlab"),
    ("GitHub",              "github"),
    ("CircleCI",            "circleci"),
    ("Travis CI",           "travis"),
    ("Buildkite",           "buildkite"),
    ("Harness",             "harness"),
    ("Codefresh",           "codefresh"),
    ("Argo",                "argoproj"),
    ("Flux",                "weaveworks"),
    ("Weaveworks",          "weaveworks"),
    ("Solo.io",             "solo"),
    ("Tetrate",             "tetrate"),
    ("Istio",               "solo"),
    ("Kong",                "kong"),
    ("Traefik",             "traefiklabs"),
    ("NGINX",               "nginx"),
    ("HAProxy",             "haproxy"),
    ("Envoy",               "envoy"),
    ("Linkerd",             "buoyant"),
    ("Buoyant",             "buoyant"),

    # ── DEVTOOLS / DEVELOPER PRODUCTIVITY ───────────────────
    ("Replit",              "replit"),
    ("Retool",              "retool"),
    ("Appsmith",            "appsmith"),
    ("Airplane",            "airplanehq"),
    ("Linear",              "linear"),
    ("Height",              "heightapp"),
    ("Shortcut",            "shortcut"),
    ("Jira",                "atlassian"),
    ("Atlassian",           "atlassian"),
    ("Confluence",          "atlassian"),
    ("Notion",              "notion"),
    ("Coda",                "coda"),
    ("Airtable",            "airtable"),
    ("Monday",              "mondaydotcom"),
    ("Asana",               "asana"),
    ("ClickUp",             "clickup"),
    ("Todoist",             "doist"),
    ("Basecamp",            "basecamp"),
    ("Trello",              "atlassian"),
    ("Miro",                "miro"),
    ("Figma",               "figma"),
    ("Sketch",              "sketch"),
    ("InVision",            "invision"),
    ("Maze",                "maze"),
    ("UserTesting",         "usertesting"),
    ("Lookback",            "lookback"),
    ("FullStory",           "fullstory"),
    ("LogRocket",           "logrocket"),
    ("Hotjar",              "hotjar"),
    ("Heap",                "heap"),
    ("Amplitude",           "amplitude"),
    ("Mixpanel",            "mixpanel"),
    ("Segment",             "segment"),
    ("Rudderstack",         "rudderstack"),
    ("mParticle",           "mparticle"),
    ("Iterable",            "iterable"),
    ("Braze",               "braze"),
    ("Attentive",           "attentive"),
    ("Klaviyo",             "klaviyo"),
    ("Sendgrid",            "sendgrid"),
    ("Mailchimp",           "mailchimp"),
    ("Customer.io",         "customerio"),
    ("ActiveCampaign",      "activecampaign"),
    ("HubSpot",             "hubspot"),
    ("Marketo",             "marketo"),
    ("Pardot",              "pardot"),
    ("Salesforce",          "salesforce"),
    ("Zendesk",             "zendesk"),
    ("Intercom",            "intercom"),
    ("Freshworks",          "freshworks"),
    ("Kustomer",            "kustomer"),
    ("Front",               "frontapp"),
    ("Gladly",              "gladly"),
    ("Gorgias",             "gorgias"),
    ("Re:amaze",            "reamaze"),
    ("Help Scout",          "helpscout"),
    ("Groove",              "groove"),
    ("Kayako",              "kayako"),
    ("Zoho",                "zoho"),

    # ── SALES / REVENUE TOOLS ───────────────────────────────
    ("Gong",                "gong"),
    ("Chorus",              "chorus"),
    ("Salesloft",           "salesloft"),
    ("Outreach",            "outreach"),
    ("Apollo",              "apolloio"),
    ("ZoomInfo",            "zoominfo"),
    ("Clearbit",            "clearbit"),
    ("Demandbase",          "demandbase"),
    ("6sense",              "6sense"),
    ("Bombora",             "bombora"),
    ("G2",                  "g2crowd"),
    ("TrustRadius",         "trustradius"),
    ("Crossbeam",           "crossbeam"),
    ("Clari",               "clari"),
    ("Boostup",             "boostup"),
    ("People.ai",           "peopleai"),
    ("Ebsta",               "ebsta"),
    ("Revenue Grid",        "revenuegrid"),
    ("Wingman",             "wingman"),
    ("Refract",             "refract"),
    ("Aviso",               "aviso"),
    ("Collective",          "collectivei"),
    ("SetSail",             "setsail"),
    ("Dooly",               "dooly"),
    ("Grain",               "getgrain"),
    ("Fathom",              "fathomhq"),
    ("Otter.ai",            "otterai"),
    ("Fireflies",           "fireflies"),
    ("Loom",                "loom"),
    ("Vidyard",             "vidyard"),
    ("Drift",               "drift"),
    ("Qualified",           "qualified"),
    ("Chili Piper",         "chilipiper"),
    ("Calendly",            "calendly"),
    ("Acuity",              "acuity"),
    ("Oncehub",             "oncehub"),
    ("Hubspot",             "hubspot"),
    ("Pipedrive",           "pipedrive"),
    ("Close",               "close"),
    ("Copper",              "copper"),
    ("Capsule",             "capsule"),
    ("Nutshell",            "nutshell"),
    ("Insightly",           "insightly"),
    ("Nimble",              "nimble"),
    ("Streak",              "streak"),
    ("Freshsales",          "freshworks"),

    # ── ECOMMERCE / RETAIL ──────────────────────────────────
    ("Shopify",             "shopify"),
    ("BigCommerce",         "bigcommerce"),
    ("WooCommerce",         "woocommerce"),
    ("Magento",             "magento"),
    ("Commercetools",       "commercetools"),
    ("Elastic Path",        "elasticpath"),
    ("Fabric",              "fabriccommerce"),
    ("Chord",               "chord"),
    ("Bolt",                "bolt"),
    ("Fast",                "fast"),
    ("Sezzle",              "sezzle"),
    ("Afterpay",            "afterpay"),
    ("Klarna",              "klarna"),
    ("Zip",                 "ziphq"),
    ("Splitit",             "splitit"),
    ("Bread",               "breadfinance"),
    ("Paidy",               "paidy"),
    ("Yotpo",               "yotpo"),
    ("Okendo",              "okendo"),
    ("Stamped",             "stamped"),
    ("Loyalty Lion",        "loyaltylion"),
    ("Smile.io",            "smile"),
    ("Gorgias",             "gorgias"),
    ("Klayvio",             "klaviyo"),
    ("Omnisend",            "omnisend"),
    ("Drip",                "drip"),
    ("Privy",               "privy"),
    ("Poptin",              "poptin"),
    ("Justuno",             "justuno"),
    ("Optinmonster",        "optinmonster"),
    ("Sumo",                "sumo"),
    ("Recart",              "recart"),
    ("Postscript",          "postscript"),
    ("Attentive",           "attentive"),
    ("SMSBump",             "smsbump"),

    # ── MARKETPLACE / ON-DEMAND ─────────────────────────────
    ("Airbnb",              "airbnb"),
    ("DoorDash",            "doordash"),
    ("Instacart",           "instacart"),
    ("Lyft",                "lyft"),
    ("Lime",                "lime"),
    ("Bird",                "bird"),
    ("Spin",                "spin"),
    ("Voi",                 "voi"),
    ("Tier",                "tier"),
    ("Superpedestrian",     "superpedestrian"),
    ("Wheels",              "wheels"),
    ("Helbiz",              "helbiz"),
    ("Getaround",           "getaround"),
    ("Turo",                "turo"),
    ("HyreCar",             "hyrecar"),
    ("Outdoorsy",           "outdoorsy"),
    ("RVshare",             "rvshare"),
    ("Vacasa",              "vacasa"),
    ("Sonder",              "sonder"),
    ("Landing",             "landing"),
    ("Blueground",          "blueground"),
    ("Zeus Living",         "zeusliving"),
    ("Furnished Finder",    "furnishedfinder"),
    ("Homeaway",            "homeaway"),
    ("VRBO",                "vrbo"),
    ("Hipcamp",             "hipcamp"),
    ("Outdoorsy",           "outdoorsy"),
    ("Campspot",            "campspot"),
    ("Hipcamp",             "hipcamp"),
    ("Glamping Hub",        "glampinghub"),
    ("Tentrr",              "tentrr"),
    ("Getaway",             "getaway"),
    ("Cabana",              "cabana"),
    ("Spot",                "spot"),

    # ── HEALTHCARE / HEALTHTECH ─────────────────────────────
    ("Oscar Health",        "oscar"),
    ("Clover Health",       "cloverhealth"),
    ("Alignment Health",    "alignmenthealthplan"),
    ("Devoted Health",      "devoted"),
    ("Bright Health",       "brighthealthgroup"),
    ("Centivo",             "centivo"),
    ("Bind",                "bind"),
    ("Sana Benefits",       "sanabenefits"),
    ("Nomi Health",         "nomihealth"),
    ("HealthMarkets",       "healthmarkets"),
    ("GoHealth",            "gohealth"),
    ("eHealth",             "ehealth"),
    ("Health IQ",           "healthiq"),
    ("Policygenius",        "policygenius"),
    ("Ladder",              "ladderlife"),
    ("Bestow",              "bestow"),
    ("Ethos",               "ethos"),
    ("Haven Life",          "havenlife"),
    ("Fabric",              "meetfabric"),
    ("Modern Health",       "modernhealth"),
    ("Spring Health",       "springhealth"),
    ("Lyra Health",         "lyrahealth"),
    ("Ginger",              "ginger"),
    ("Cerebral",            "cerebral"),
    ("Talkspace",           "talkspace"),
    ("BetterHelp",          "betterhelp"),
    ("Calm",                "calm"),
    ("Headspace",           "headspace"),
    ("Woebot",              "woebot"),
    ("Noom",                "noom"),
    ("Hinge Health",        "hingehealth"),
    ("Kaia Health",         "kaiahealth"),
    ("Sword Health",        "swordhealth"),
    ("RecoveryOne",         "recoveryone"),
    ("Omada Health",        "omadahealth"),
    ("Virta Health",        "virtahealth"),
    ("Livongo",             "livongo"),
    ("Teladoc",             "teladoc"),
    ("MDLive",              "mdlive"),
    ("Doctor on Demand",    "doctorondemand"),
    ("98point6",            "98point6"),
    ("Carbon Health",       "carbonhealth"),
    ("One Medical",         "onemedical"),
    ("Forward Health",      "forward"),
    ("Parsley Health",      "parsleyhealth"),
    ("Ro",                  "ro"),
    ("Hims",                "hims"),
    ("Keeps",               "keeps"),
    ("Nurx",                "nurx"),
    ("Done",                "doneglobal"),
    ("Cerebral",            "cerebral"),
    ("Alto Pharmacy",       "alto"),
    ("Truepill",            "truepill"),
    ("NimbleRx",            "nimblerx"),
    ("Capsule",             "capsule"),
    ("PillPack",            "pillpack"),
    ("Amazon Pharmacy",     "amazon"),
    ("Benchling",           "benchling"),
    ("Veeva",               "veeva"),
    ("Medidata",            "medidata"),
    ("Flatiron Health",     "flatiron"),
    ("Tempus",              "tempus"),
    ("Foundation Medicine", "foundationmedicine"),
    ("Guardant Health",     "guardanthealth"),
    ("Grail",               "grail"),
    ("Illumina",            "illumina"),
    ("Pacific Biosciences", "pacificbiosciences"),
    ("Oxford Nanopore",     "nanoporetech"),
    ("10x Genomics",        "10xgenomics"),
    ("Twist Bioscience",    "twistbioscience"),
    ("Ginkgo Bioworks",     "ginkgobioworks"),
    ("Zymergen",            "zymergen"),
    ("Recursion",           "recursionpharma"),
    ("Insilico Medicine",   "insilico"),
    ("Atomwise",            "atomwise"),
    ("Schrödinger",         "schrodinger"),
    ("Relay Therapeutics",  "relaytx"),
    ("Generate Biomedicines","generatebiomedicines"),
    ("Absci",               "absci"),

    # ── EDTECH ──────────────────────────────────────────────
    ("Duolingo",            "duolingo"),
    ("Coursera",            "coursera"),
    ("Udemy",               "udemy"),
    ("Udacity",             "udacity"),
    ("Pluralsight",         "pluralsight"),
    ("Skillshare",          "skillshare"),
    ("MasterClass",         "masterclass"),
    ("Brilliant",           "brilliant"),
    ("Khan Academy",        "khanacademy"),
    ("Chegg",               "chegg"),
    ("Quizlet",             "quizlet"),
    ("Kahoot",              "kahoot"),
    ("Nearpod",             "nearpod"),
    ("Pear Deck",           "peardeck"),
    ("Newsela",             "newsela"),
    ("IXL Learning",        "ixl"),
    ("Renaissance",         "renaissance"),
    ("Powerschool",         "powerschool"),
    ("Schoology",           "schoology"),
    ("Canvas",              "instructure"),
    ("Instructure",         "instructure"),
    ("Blackboard",          "blackboard"),
    ("D2L",                 "d2l"),
    ("Moodle",              "moodle"),
    ("Handshake",           "handshake"),
    ("Chegg",               "chegg"),
    ("Course Hero",         "coursehero"),
    ("Chegg Tutors",        "chegg"),
    ("Wyzant",              "wyzant"),
    ("Varsity Tutors",      "varsitytutors"),
    ("Preply",              "preply"),
    ("iTalki",              "italki"),
    ("Verbling",            "verbling"),
    ("Cambly",              "cambly"),
    ("Babbel",              "babbel"),
    ("Rosetta Stone",       "rosettastone"),
    ("Pimsleur",            "pimsleur"),
    ("Lingoda",             "lingoda"),
    ("OutSchool",           "outschool"),
    ("Juni Learning",       "junilearning"),
    ("Synthesis",           "synthesis"),
    ("Primer",              "primer"),
    ("Sora Schools",        "soraschools"),
    ("Alpha School",        "alpha"),

    # ── HR TECH / PEOPLE OPS ────────────────────────────────
    ("Gusto",               "gusto"),
    ("Rippling",            "rippling"),
    ("Lattice",             "lattice"),
    ("Culture Amp",         "cultureamp"),
    ("Leapsome",            "leapsome"),
    ("Betterworks",         "betterworks"),
    ("Reflektive",          "reflektive"),
    ("Workday",             "workday"),
    ("Greenhouse",          "greenhouse"),
    ("Lever",               "lever"),
    ("Ashby",               "ashby"),
    ("Recruitee",           "recruitee"),
    ("Workable",            "workable"),
    ("JazzHR",              "jazzhr"),
    ("BambooHR",            "bamboohr"),
    ("Namely",              "namely"),
    ("Zenefits",            "zenefits"),
    ("Justworks",           "justworks"),
    ("TriNet",              "trinet"),
    ("ADP",                 "adp"),
    ("Paychex",             "paychex"),
    ("Paylocity",           "paylocity"),
    ("Paycom",              "paycom"),
    ("Ceridian",            "ceridian"),
    ("UKG",                 "ukg"),
    ("Kronos",              "kronos"),
    ("Deputy",              "deputy"),
    ("When I Work",         "wheniwork"),
    ("Homebase",            "homebase"),
    ("7shifts",             "7shifts"),
    ("HotSchedules",        "hotschedules"),
    ("Sling",               "getsling"),
    ("Shyft",               "myshyft"),
    ("Quinyx",              "quinyx"),
    ("Humanity",            "humanity"),
    ("TimeForge",           "timeforge"),
    ("Planday",             "planday"),
    ("Agendrix",            "agendrix"),

    # ── PROPTECH / REAL ESTATE ──────────────────────────────
    ("Opendoor",            "opendoor"),
    ("Offerpad",            "offerpad"),
    ("Knock",               "knockcrm"),
    ("Orchard",             "orchard"),
    ("Flyhomes",            "flyhomes"),
    ("Homeward",            "homeward"),
    ("Ribbon",              "ribbon"),
    ("Endpoint",            "endpoint"),
    ("Spruce",              "spruce"),
    ("States Title",        "statestitle"),
    ("Doma",                "doma"),
    ("Mynd",                "mynd"),
    ("Belong",              "belong"),
    ("Doorstead",           "doorstead"),
    ("Poplar",              "poplar"),
    ("Roofstock",           "roofstock"),
    ("Arrived Homes",       "arrived"),
    ("Fundrise",            "fundrise"),
    ("Cadre",               "cadre"),
    ("CrowdStreet",         "crowdstreet"),
    ("RealPage",            "realpage"),
    ("Yardi",               "yardi"),
    ("AppFolio",            "appfolio"),
    ("Buildium",            "buildium"),
    ("Rentec Direct",       "rentecdirect"),
    ("TenantCloud",         "tenantcloud"),
    ("Cozy",                "cozy"),
    ("Avail",               "avail"),
    ("Turbotenant",         "turbotenant"),
    ("Rentspree",           "rentspree"),
    ("Showmojo",            "showmojo"),
    ("Rently",              "rently"),
    ("Leaselock",           "leaselock"),
    ("Obligo",              "obligo"),
    ("Rhino",               "sayrhino"),
    ("Deposit IQ",          "depositiq"),
    ("LeaseLock",           "leaselock"),
    ("Jetty",               "jetty"),
    ("TheGuarantors",       "theguarantors"),

    # ── LOGISTICS / SUPPLY CHAIN ────────────────────────────
    ("Flexport",            "flexport"),
    ("Convoy",              "convoy"),
    ("Transfix",            "transfix"),
    ("Loadsmart",           "loadsmart"),
    ("Turvo",               "turvo"),
    ("Samsara",             "samsara"),
    ("Motive",              "gomotive"),
    ("KeepTruckin",         "keeptruckin"),
    ("Platform Science",    "platformscience"),
    ("Netradyne",           "netradyne"),
    ("Lytx",                "lytx"),
    ("SmartDrive",          "smartdrive"),
    ("Omnitracs",           "omnitracs"),
    ("Trimble",             "trimble"),
    ("Verizon Connect",     "verizonconnect"),
    ("Geotab",              "geotab"),
    ("Spireon",             "spireon"),
    ("Orbcomm",             "orbcomm"),
    ("CalAmp",              "calamp"),
    ("Powerfleet",          "powerfleet"),
    ("OneStop Systems",     "onestopts"),
    ("Axle",                "axle"),
    ("Shippo",              "shippo"),
    ("EasyPost",            "easypost"),
    ("Shipbob",             "shipbob"),
    ("Darkstore",           "darkstore"),
    ("Fabric",              "fabriccommerce"),
    ("Ware2Go",             "ware2go"),
    ("Deliverr",            "deliverr"),
    ("Whiplash",            "whiplash"),
    ("ShipHero",            "shiphero"),
    ("ShipStation",         "shipstation"),
    ("Ordoro",              "ordoro"),
    ("Linnworks",           "linnworks"),
    ("Skubana",             "skubana"),
    ("Stord",               "stord"),
    ("Flexe",               "flexe"),
    ("Ware2Go",             "ware2go"),
    ("XPO Logistics",       "xpo"),
    ("Echo Global",         "echo"),
    ("Coyote",              "coyote"),
    ("GlobalTranz",         "globaltranz"),
    ("MoLo Solutions",      "molosolutions"),
    ("Arrive Logistics",    "arrivelogistics"),
    ("Spot",                "spotfreight"),
    ("Coyote",              "coyote"),
    ("Echo",                "echo"),
    ("Uber Freight",        "uberfreight"),
    ("Amazon Freight",      "amazon"),

    # ── SECURITY / CYBERSECURITY ────────────────────────────
    ("Crowdstrike",         "crowdstrike"),
    ("SentinelOne",         "sentinelone"),
    ("Palo Alto Networks",  "paloaltonetworks"),
    ("Zscaler",             "zscaler"),
    ("Okta",                "okta"),
    ("Ping Identity",       "pingidentity"),
    ("Auth0",               "auth0"),
    ("OneLogin",            "onelogin"),
    ("Duo Security",        "duo"),
    ("Yubico",              "yubico"),
    ("Vanta",               "vanta"),
    ("Drata",               "drata"),
    ("Secureframe",         "secureframe"),
    ("Tugboat Logic",       "tugboatlogic"),
    ("Hyperproof",          "hyperproof"),
    ("LogicGate",           "logicgate"),
    ("Reciprocity",         "reciprocity"),
    ("OneTrust",            "onetrust"),
    ("TrustArc",            "trustarc"),
    ("BigID",               "bigid"),
    ("Immuta",              "immuta"),
    ("Privacera",           "privacera"),
    ("Securiti",            "securiti"),
    ("Dataguise",           "dataguise"),
    ("Varonis",             "varonis"),
    ("Code42",              "code42"),
    ("Digital Guardian",    "digitalguardian"),
    ("Forcepoint",          "forcepoint"),
    ("Nightfall",           "nightfall"),
    ("Tessian",             "tessian"),
    ("Abnormal Security",   "abnormalsecurity"),
    ("Proofpoint",          "proofpoint"),
    ("Mimecast",            "mimecast"),
    ("Area 1 Security",     "area1security"),
    ("Darktrace",           "darktrace"),
    ("Vectra",              "vectra"),
    ("Exabeam",             "exabeam"),
    ("LogRhythm",           "logrhythm"),
    ("Securonix",           "securonix"),
    ("Sumo Logic",          "sumologic"),
    ("Devo",                "devo"),
    ("Hunters",             "hunters"),
    ("Cybereason",          "cybereason"),
    ("Deep Instinct",       "deepinstinct"),
    ("Morphisec",           "morphisec"),
    ("Illumio",             "illumio"),
    ("Guardicore",          "guardicore"),
    ("Veriato",             "veriato"),
    ("ObserveIT",           "observeit"),

    # ── MEDIA / CONTENT ─────────────────────────────────────
    ("Spotify",             "spotify"),
    ("Pandora",             "pandora"),
    ("SoundCloud",          "soundcloud"),
    ("Deezer",              "deezer"),
    ("Tidal",               "tidal"),
    ("Apple Music",         "apple"),
    ("YouTube Music",       "google"),
    ("Amazon Music",        "amazon"),
    ("Napster",             "napster"),
    ("Audiomack",           "audiomack"),
    ("Bandcamp",            "bandcamp"),
    ("Soundtrap",           "soundtrap"),
    ("Splice",              "splice"),
    ("BeatStars",           "beatstars"),
    ("Landr",               "landr"),
    ("Distrokid",           "distrokid"),
    ("TuneCore",            "tunecore"),
    ("CD Baby",             "cdbaby"),
    ("Amuse",               "amuse"),
    ("Stem",                "stem"),
    ("Chartmetric",         "chartmetric"),
    ("Soundcharts",         "soundcharts"),
    ("Next Big Sound",      "nextbigsound"),
    ("Spotify for Artists", "spotify"),
    ("Chartio",             "chartio"),
    ("Buzzfeed",            "buzzfeed"),
    ("Vox Media",           "voxmedia"),
    ("Vice Media",          "vice"),
    ("The Atlantic",        "theatlantic"),
    ("The Guardian",        "theguardian"),
    ("The New York Times",  "nytimes"),
    ("Washington Post",     "washingtonpost"),
    ("Wall Street Journal", "wsj"),
    ("Bloomberg",           "bloomberg"),
    ("Reuters",             "reuters"),
    ("AP",                  "ap"),
    ("NPR",                 "npr"),
    ("PBS",                 "pbs"),
    ("CNN",                 "cnn"),
    ("BBC",                 "bbc"),
    ("ESPN",                "espn"),
    ("Fox Sports",          "foxsports"),
    ("NBC Sports",          "nbcsports"),
    ("Turner Sports",       "turnersports"),
    ("Stadium",             "stadiumtv"),
    ("The Athletic",        "theathletic"),
    ("Fansided",            "fansided"),
    ("Bleacher Report",     "bleacherreport"),
    ("SB Nation",           "sbnation"),
    ("Deadspin",            "deadspin"),

    # ── GAMING ──────────────────────────────────────────────
    ("Riot Games",          "riotgames"),
    ("Epic Games",          "epicgames"),
    ("Unity",               "unity"),
    ("Niantic",             "niantic"),
    ("Scopely",             "scopely"),
    ("Jam City",            "jamcity"),
    ("Kabam",               "kabam"),
    ("Big Fish Games",      "bigfishgames"),
    ("Glu Mobile",          "glu"),
    ("Playtika",            "playtika"),
    ("Zynga",               "zynga"),
    ("Electronic Arts",     "ea"),
    ("Activision",          "activision"),
    ("Blizzard",            "blizzard"),
    ("2K Games",            "2k"),
    ("Take-Two",            "taketwo"),
    ("Ubisoft",             "ubisoft"),
    ("CD Projekt",          "cdprojektred"),
    ("Square Enix",         "squareenix"),
    ("Sega",                "sega"),
    ("Konami",              "konami"),
    ("Bandai Namco",        "bandainamco"),
    ("Capcom",              "capcom"),
    ("Bethesda",            "bethesda"),
    ("id Software",         "idsoftware"),
    ("Double Fine",         "doublefine"),
    ("Insomniac",           "insomniacgames"),
    ("Naughty Dog",         "naughtydog"),
    ("Bungie",              "bungie"),
    ("Respawn",             "respawn"),
    ("Infinity Ward",       "infinityward"),
    ("Treyarch",            "treyarch"),
    ("343 Industries",      "343industries"),
    ("The Coalition",       "thecoalition"),
    ("Playground Games",    "playgroundgames"),
    ("Ninja Theory",        "ninjatheory"),
    ("Rare",                "rare"),
    ("Crystal Dynamics",    "crystaldynamics"),
    ("Eidos Montreal",      "eidosmontreal"),
    ("Deus Ex",             "deusex"),
    ("IO Interactive",      "iointeractive"),
    ("Remedy Entertainment","remedy"),
    ("Housemarque",         "housemarque"),
    ("Guerrilla Games",     "guerrilla"),
    ("Media Molecule",      "mediamolecule"),
    ("Sucker Punch",        "suckerpunch"),
    ("Santa Monica Studio", "santamonicasdudio"),

    # ── ENTERPRISE SOFTWARE ─────────────────────────────────
    ("Workiva",             "workiva"),
    ("Verint",              "verint"),
    ("NICE Systems",        "nice"),
    ("Genesys",             "genesys"),
    ("Avaya",               "avaya"),
    ("Five9",               "five9"),
    ("Talkdesk",            "talkdesk"),
    ("Dialpad",             "dialpad"),
    ("RingCentral",         "ringcentral"),
    ("8x8",                 "8x8"),
    ("Vonage",              "vonage"),
    ("Twilio",              "twilio"),
    ("MessageBird",         "messagebird"),
    ("Bandwidth",           "bandwidth"),
    ("Plivo",               "plivo"),
    ("Nexmo",               "vonage"),
    ("Sinch",               "sinch"),
    ("Infobip",             "infobip"),
    ("Kaleyra",             "kaleyra"),
    ("Clicksend",           "clicksend"),
    ("EZTexting",           "eztexting"),
    ("SimpleTexting",       "simpletexting"),
    ("Textedly",            "textedly"),
    ("Sakari",              "sakari"),
    ("Salesmsg",            "salesmsg"),
    ("Podium",              "podium"),
    ("Birdeye",             "birdeye"),
    ("Reputation",          "reputation"),
    ("Yext",                "yext"),
    ("Uberall",             "uberall"),
    ("Rio SEO",             "rioseo"),
    ("Moz",                 "moz"),
    ("Semrush",             "semrush"),
    ("Ahrefs",              "ahrefs"),
    ("Majestic",            "majestic"),
    ("Screaming Frog",      "screamingfrog"),
    ("BrightEdge",          "brightedge"),
    ("Conductor",           "conductor"),
    ("Searchmetrics",       "searchmetrics"),
    ("Botify",              "botify"),
    ("Deepcrawl",           "deepcrawl"),
    ("Sitebulb",            "sitebulb"),
    ("Oncrawl",             "oncrawl"),
    ("Lumar",               "lumar"),
    ("ContentKing",         "contentking"),
    ("Seolyzer",            "seolyzer"),
    ("Ryte",                "ryte"),
    ("Sistrix",             "sistrix"),
    ("Authoritas",          "authoritas"),
    ("Advanced Web Ranking","advancedwebranking"),

    # ── ADDITIONAL HIGH-VALUE TARGETS ───────────────────────
    ("Checkr",              "checkr"),
    ("Persona",             "persona"),
    ("Onfido",              "onfido"),
    ("Socure",              "socure"),
    ("Jumio",               "jumio"),
    ("Trulioo",             "trulioo"),
    ("Alloy",               "alloy"),
    ("Unit21",              "unit21"),
    ("Sardine",             "sardine"),
    ("Sift",                "sift"),
    ("Kount",               "kount"),
    ("Forter",              "forter"),
    ("Signifyd",            "signifyd"),
    ("Riskified",           "riskified"),
    ("NS8",                 "ns8"),
    ("Bolt",                "bolt"),
    ("NoFraud",             "nofraud"),
    ("ClearSale",           "clearsale"),
    ("Featurespace",        "featurespace"),
    ("Simility",            "simility"),
    ("DataVisor",           "datavisor"),
    ("Fraugster",           "fraugster"),
    ("Stripe Radar",        "stripe"),
    ("Recurly",             "recurly"),
    ("Chargebee",           "chargebee"),
    ("Paddle",              "paddle"),
    ("FastSpring",          "fastspring"),
    ("Zuora",               "zuora"),
    ("Maxio",               "maxio"),
    ("Chargify",            "chargify"),
    ("Braintree",           "braintree"),
    ("Spreedly",            "spreedly"),
    ("Primer",              "primer"),
    ("Gr4vy",               "gr4vy"),
    ("Exact Payments",      "exactpayments"),
    ("Stax",                "stax"),
    ("Finix",               "finix"),
    ("Payrix",              "payrix"),
    ("Till Payments",       "till"),
    ("Nmi",                 "nmi"),
    ("Clearent",            "clearent"),
    ("Priority",            "prioritytech"),
    ("Paysafe",             "paysafe"),
    ("Nuvei",               "nuvei"),
    ("i2c",                 "i2cinc"),
    ("Galileo",             "galileofinancial"),
    ("Synapse",             "synapsepay"),
    ("Unit",                "unit"),
    ("Treasury Prime",      "treasuryprime"),
    ("Column",              "column"),
    ("Grasshopper",         "grasshopper"),
    ("Relay",               "relayfi"),
    ("Nearside",            "nearside"),
    ("Lili",                "lili"),
    ("Found",               "found"),
    ("Bluevine",            "bluevine"),
    ("Fundbox",             "fundbox"),
    ("Pipe",                "pipe"),
    ("Clearco",             "clearco"),
    ("Capchase",            "capchase"),
    ("Lighter Capital",     "lightercapital"),
    ("Arc",                 "arc"),
    ("Founderpath",         "founderpath"),
    ("Boopos",              "boopos"),
    ("Microacquire",        "microacquire"),
    ("Acquire",             "acquire"),
    ("Flippa",              "flippa"),
    ("Empire Flippers",     "empireflippers"),
    ("Quiet Light",         "quietlight"),
    ("FE International",    "feinternational"),
]

def get_conn():
    return psycopg2.connect(
        host=os.getenv("PGHOST", "localhost"),
        port=int(os.getenv("PGPORT", "5432")),
        dbname=os.getenv("PGDATABASE", "job_analytics"),
        user=os.getenv("PGUSER"),
        password=os.getenv("PGPASSWORD"),
    )

def _cid(ats: str, token: str) -> str:
    h = hashlib.md5(f"{ats}|{token}".encode()).hexdigest()[:10]
    return f"DC{h}"

def insert_companies(cur, apply: bool) -> int:
    now = datetime.now(timezone.utc)
    # Deduplicate the list by token
    seen = set()
    deduped = []
    for name, token in COMPANIES:
        if token not in seen:
            seen.add(token)
            deduped.append((name, token))

    log.info(f"Inserting {len(deduped)} unique companies (0 active_roles — refresh will probe them)")
    inserted = 0
    for name, token in deduped:
        if apply:
            try:
                cur.execute(
                    """
                    INSERT INTO discovered_companies
                        (company_id, company_name, ats_source, board_token,
                         discovery_source, first_seen_at, last_seen_at,
                         active_roles, total_seen, enabled)
                    VALUES (%s,%s,'greenhouse',%s,'manual',%s,%s,0,0,true)
                    ON CONFLICT (ats_source, board_token) DO NOTHING
                    """,
                    (_cid("greenhouse", token), name, token, now, now)
                )
                if cur.rowcount > 0:
                    inserted += 1
            except Exception as e:
                log.warning(f"  Skip {name} ({token}): {e}")
                cur.connection.rollback()
        else:
            inserted += 1

    return inserted

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    conn = get_conn()
    conn.autocommit = False
    cur = conn.cursor(cursor_factory=DictCursor)

    n = insert_companies(cur, args.apply)

    if args.apply:
        conn.commit()
        log.info(f"✅ Inserted {n} new companies into discovered_companies")
        log.info("Next step: python python/discover_companies.py --apply --source refresh")
        log.info("That will probe each company and update active_roles counts (takes ~10 min)")
    else:
        conn.rollback()
        log.info(f"Dry run — would insert {n} new companies. Add --apply to write.")

    cur.close()
    conn.close()

if __name__ == "__main__":
    import argparse
    main()
